- MySQL Script generated by MySQL Workbench
-- Sun Jul 19 20:08:30 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema BDPANADERIALEOS
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BDPANADERIALEOS
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BDPANADERIALEOS` DEFAULT CHARACTER SET utf8 ;
USE `BDPANADERIALEOS` ;

-- -----------------------------------------------------
-- Table `BDPANADERIALEOS`.`VENTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDPANADERIALEOS`.`VENTA` (
  `venta_id` CHAR(20) NOT NULL,
  `fecha` DATE NULL,
  PRIMARY KEY (`venta_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `BDPANADERIALEOS`.`TIPO_COMPROBANTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDPANADERIALEOS`.`TIPO_COMPROBANTE` (
  `tipoComprobante_id` INT NOT NULL AUTO_INCREMENT,
  `comprobante` VARCHAR(45) NULL,
  PRIMARY KEY (`tipoComprobante_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `BDPANADERIALEOS`.`PRODUCTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDPANADERIALEOS`.`PRODUCTO` (
  `producto_id` CHAR(10) NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `presentacion` VARCHAR(45) NULL,
  `stock` VARCHAR(45) NULL,
  `PRODUCTOcol` VARCHAR(45) NULL,
  PRIMARY KEY (`producto_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDPANADERIALEOS`.`INSUMO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDPANADERIALEOS`.`INSUMO` (
  `insumo_id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`insumo_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDPANADERIALEOS`.`SECCION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDPANADERIALEOS`.`SECCION` (
  `seccion_id` INT NOT NULL AUTO_INCREMENT,
  `seccion` VARCHAR(45) NULL,
  PRIMARY KEY (`seccion_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `BDPANADERIALEOS`.`CATEGORIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDPANADERIALEOS`.`CATEGORIA` (
  `categoria_id` INT NOT NULL AUTO_INCREMENT,
  `categoria` VARCHAR(45) NULL,
  `descripcion` VARCHAR(150) NULL,
  `estado` VARCHAR(45) NULL,
  PRIMARY KEY (`categoria_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `BDPANADERIALEOS`.`DETALLE_VENTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDPANADERIALEOS`.`DETALLE_VENTA` (
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `BDPANADERIALEOS`.`CAJA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDPANADERIALEOS`.`CAJA` (
  `caja_id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`caja_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `BDPANADERIALEOS`.`MOVIMIENTOS_CAJA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDPANADERIALEOS`.`MOVIMIENTOS_CAJA` (
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `BDPANADERIALEOS`.`COLABORADOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDPANADERIALEOS`.`COLABORADOR` (
  `colaborador_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  `aPaterno` VARCHAR(80) NULL,
  `aMaterno` VARCHAR(80) NULL,
  `dni` CHAR(8) NULL,
  `direccion` VARCHAR(150) NULL,
  `nCelular` CHAR(9) NULL,
  `fIngreso` DATE NULL,
  `fCreacion` DATE NULL,
  PRIMARY KEY (`colaborador_id`))
ENGINE = CSV
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `BDPANADERIALEOS`.`CARGO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDPANADERIALEOS`.`CARGO` (
  `cargo_id` INT NOT NULL AUTO_INCREMENT,
  `cargo` VARCHAR(100) NULL,
  `descripcion` VARCHAR(100) NULL,
  `fCreacion` DATE NULL,
  PRIMARY KEY (`cargo_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `BDPANADERIALEOS`.`USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDPANADERIALEOS`.`USUARIO` (
  `usuario_id` INT NOT NULL,
  `user` VARCHAR(8) NULL,
  `pass` VARCHAR(25) NULL,
  `mail` VARCHAR(100) NULL,
  `fCreacion` DATE NULL,
  PRIMARY KEY (`usuario_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `BDPANADERIALEOS`.`MAQUINA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDPANADERIALEOS`.`MAQUINA` (
  `maquina_id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`maquina_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `BDPANADERIALEOS`.`PRODUCCCION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDPANADERIALEOS`.`PRODUCCCION` (
  `produccion_id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`produccion_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `BDPANADERIALEOS`.`IMAGEN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDPANADERIALEOS`.`IMAGEN` (
  `imagen_id` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`imagen_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `BDPANADERIALEOS`.`TIPO_CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDPANADERIALEOS`.`TIPO_CLIENTE` (
  `tipoCliente_id` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(60) NULL,
  `descripcion` VARCHAR(80) NULL,
  PRIMARY KEY (`tipoCliente_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `BDPANADERIALEOS`.`DETALLE_PRODUCCION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDPANADERIALEOS`.`DETALLE_PRODUCCION` (
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `BDPANADERIALEOS`.`COMPRABODEGA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDPANADERIALEOS`.`COMPRABODEGA` (
  `comprabod_id` CHAR(15) NOT NULL,
  PRIMARY KEY (`comprabod_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `BDPANADERIALEOS`.`PROVEEDOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDPANADERIALEOS`.`PROVEEDOR` (
  `proveedor_id` CHAR(15) NOT NULL,
  `rason` VARCHAR(100) NULL,
  `ruc` CHAR(11) NULL,
  `direccion` VARCHAR(100) NULL,
  `representante` VARCHAR(100) NULL,
  `email` VARCHAR(100) NULL,
  `nCelular` CHAR(9) NULL,
  `nFono` CHAR(9) NULL,
  `referencia` VARCHAR(45) NULL,
  PRIMARY KEY (`proveedor_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `BDPANADERIALEOS`.`PEDIDO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDPANADERIALEOS`.`PEDIDO` (
  `pedido_id` CHAR(20) NOT NULL,
  PRIMARY KEY (`pedido_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `BDPANADERIALEOS`.`DETALLE_PEDIDO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDPANADERIALEOS`.`DETALLE_PEDIDO` (
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `BDPANADERIALEOS`.`RECETA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDPANADERIALEOS`.`RECETA` (
  `recerta_id` CHAR(10) NOT NULL,
  PRIMARY KEY (`recerta_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `BDPANADERIALEOS`.`CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDPANADERIALEOS`.`CLIENTE` (
  `cliente_id` CHAR(15) NOT NULL,
  `nombre_razon` VARCHAR(150) NULL,
  `direccion` VARCHAR(100) NULL,
  `documento_identi` VARCHAR(45) NULL,
  `alias` VARCHAR(45) NULL,
  `referencia` VARCHAR(45) NULL,
  `representante` VARCHAR(45) NULL,
  `nCelular` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `fCreacion` VARCHAR(45) NULL,
  `registro` VARCHAR(45) NULL,
  PRIMARY KEY (`cliente_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDPANADERIALEOS`.`IDENTIFICACION_CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDPANADERIALEOS`.`IDENTIFICACION_CLIENTE` (
  `identificacion_id` INT NOT NULL,
  `tipo_identificacion` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `fCreacion` VARCHAR(45) NULL,
  PRIMARY KEY (`identificacion_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDPANADERIALEOS`.`TURNO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDPANADERIALEOS`.`TURNO` (
  `turno_id` INT NOT NULL,
  `turno` VARCHAR(45) NULL,
  PRIMARY KEY (`turno_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
